StoneGameII:	StoneGameII.cpp
	g++ -std=c++23 -g -Wall -o StoneGameII StoneGameII.cpp
	./StoneGameII

topSolution:	topSolution.cpp
	g++ -std=c++23 -g -Wall -o topSolution topSolution.cpp
	./topSolution

clean:
	rm -f StoneGameII topSolution
	clear