PostOrder:	PostOrder.cpp
	g++ -std=c++23 -g -o PostOrder PostOrder.cpp
	./PostOrder

topSolution:	topSolution.cpp
	g++ -std=c++23 -g -o topSolution topSolution.cpp
	./topSolution

clean:
	rm -f PostOrder topSolution
	clear