StringEncodeDecode:	StringEncodeDecode.cpp
	g++ -std=c++23 -g -Wall -o StringEncodeDecode StringEncodeDecode.cpp
	./StringEncodeDecode

neetcodeSolution:	neetcodeSolution.cpp
	g++ -std=c++23 -g -Wall -o neetcodeSolution neetcodeSolution.cpp
	./neetcodeSolution

clean:
	rm -f StringEncodeDecode neetcodeSolution
	clear