ValidSudoku:	ValidSudoku.cpp
	g++ -std=c++23 -g -o ValidSudoku ValidSudoku.cpp
	./ValidSudoku

topSolution:	topSolution.cpp
	g++ -std=c++23 -g -o topSolution topSolution.cpp
	./topSolution

clean:
	rm -f ValidSudoku topSolution
	clear