ContainsDuplicate:	ContainsDuplicate.cpp
	g++ -std=c++23 -g -Wall -o ContainsDuplicate ContainsDuplicate.cpp
	./ContainsDuplicate

topSolution:	topSolution.cpp
	g++ -std=c++23 -g -Wall -o topSolution topSolution.cpp
	./topSolution

clean:
	rm -f ContainsDuplicate topSolution
	clear