UglyNumberII:	UglyNumberII.cpp
	g++ -std=c++23 -Wall -g -o UglyNumberII UglyNumberII.cpp
	./UglyNumberII

topSolution:	topSolution.cpp
	g++ -std=c++23 -Wall -g -o topSolution topSolution.cpp
	./topSolution

clean:
	rm -f UglyNumberII
	rm -f topSolution
	clear