ProductOfArrayExceptSelf:	ProductOfArrayExceptSelf.cpp
	g++ -std=c++23 -g -o ProductOfArrayExceptSelf ProductOfArrayExceptSelf.cpp
	./ProductOfArrayExceptSelf

topSolution:	topSolution.cpp
	g++ -std=c++23 -g -o topSolution topSolution.cpp
	./topSolution

clean:
	rm -f ProductOfArrayExceptSelf topSolution
	clear