NTreePostOrder:	N-aryTreePostOrder.cpp
	g++ -std=c++23 -g -o NTreePostOrder N-aryTreePostOrder.cpp
	./NTreePostOrder

topSolution:	topSolution.cpp
	g++ -std=c++23 -g -o topSolution topSolution.cpp
	./topSolution

clean:
	rm -f NTreePostOrder topSolution
	clear