GroupAnagrams:	GroupAnagrams.cpp
	g++ -std=c++23 -Wall -g -o GroupAnagrams GroupAnagrams.cpp
	./GroupAnagrams

topSolution:	topSolution.cpp
	g++ -std=c++23 -Wall -g -o topSolution topSolution.cpp
	./topSolution

clean:
	rm GroupAnagrams topSolution
	clear