2KeysKeyboard:	2KeysKeyboard.cpp
	g++ -std=c++23 -g -Wall -o 2KeysKeyboard 2KeysKeyboard.cpp
	./2KeysKeyboard

topSolution:	topSolution.cpp
	g++ -std=c++23 -g -Wall -o topSolution topSolution.cpp
	./topSolution

clean:
	rm 2KeysKeyboard topSolution
	clear