LemonadeChange: LemonadeChange.cpp
	g++ -std=c++23 -Wall -g -o LemonadeChange LemonadeChange.cpp
	./LemonadeChange

topSolution:	topSolution.cpp
	g++ -std=c++23 -Wall -g -o topSolution topSolution.cpp
	./topSolution