KthLargest:	KthLargest.cpp
	g++ -std=c++23 -g -o KthLargest KthLargest.cpp
	./KthLargest

topSolution:	topSolution.cpp
	g++ -std=c++23 -g -o topSolution topSolution.cpp
	./topSolution

clean:
	rm -f KthLargest topSolution
	clear