ValidAnagram:	ValidAnagram.cpp
	g++ -std=c++23 -Wall -g -o ValidAnagram ValidAnagram.cpp
	./ValidAnagram

topSolution:	topSolution.cpp
	g++ -std=c++23 -Wall -g -o topSolution topSolution.cpp
	./topSolution

clean:
	rm -f ValidAnagram topSolution
	clear