TopKFrequentElements:	TopKFrequentElements.cpp
	g++ -std=c++23 -g -o TopKFrequentElements TopKFrequentElements.cpp
	./TopKFrequentElements

topSolution:	topSolution.cpp
	g++ -std=c++23 -g -o topSolution topSolution.cpp
	./topSolution

clean:
	rm -f TopKFrequentElements topSolution
	clear