StrangePrinter:	StrangePrinter.cpp
	g++ -std=c++23 -g -Wall -o StrangePrinter StrangePrinter.cpp
	./StrangePrinter

topSolution:	topSolution.cpp
	g++ -std=c++23 -g -Wall -o topSolution topSolution.cpp
	./topSolution

clean:
	rm StrangePrinter topSolution
	clear