TwoSum:	TwoSum.cpp
	g++ -std=c++23 -Wall -g -o TwoSum TwoSum.cpp
	./TwoSum

topSolution: topSolution.cpp
	g++ -std=c++23 -Wall -g -o topSolution topSolution.cpp
	./topSolution

clean:
	rm -f TwoSum topSolution
	clear